name: VitalCore
main: me.winflix.vitalcore.VitalCore
version: ${project.version}
api-version: 1.21
authors: [ WinFlix ]
description: Core of OverWild
commands:
  tribe:
    description: Main command of the tribes
    usage: /<command>
    aliases:
      - clan
      - team
      - tr
  vcore:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - vitalcore
      - vr
  npc:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
  skins:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - skin
  tpa:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - teleport
  tpaccept:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - teleportaccept
  tpadeny:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - teleportdeny
  spawn:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - sp
  setspawn:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - ssp
  msg:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - tell
  addons:
    description: Main command of the VitalCore
    usage: /<command>
    aliases:
      - adds